# -*- coding: utf-8 -*-
"""Kurtosis.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1puOPVU9QtxOdnqtr4CaK8sEBTSqfJyRu#scrollTo=b3w9zCR6lFeF
"""


import pandas as pd
import numpy as np

data=pd.read_csv("Housing_Data.csv")
data

print(data.columns)
Index(['Manufacturer', 'Model', 'Sales in thousands', '4-year resale value',
       'Vehicle type', 'Price in thousands', 'Engine size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb weight', 'Fuel capacity',
       'Fuel efficiency', 'Latest Launch'],
      dtype='object')

price = data['price']
kurtosis_value = price.kurt()
print("Kurtosis Value:", kurtosis_value)

#       Validation
if kurtosis_value > 0:
    print("Leptokurtic Distribution")
elif kurtosis_value < 0:
    print("Platykurtic Distribution")
else:
    print("Mesokurtic Distribution")

   Kurtosis Value: 1.9597399905771677
Leptokurtic Distribution

plt.figure(figsize=(8,5))
plt.hist(price, bins=20)
plt.title("House Price Distribution")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()

import matplotlib.pyplot as plt
x=data["Sales in thousands"]
plt.hist(x, color="blue", edgecolor="black")
plt.title("Amount")
plt.xlabel("data")
plt.ylabel("list")
plt.show()

import matplotlib.pyplot as plt
plt.scatter(data["price"], data["lotsize"])
plt.xlabel("Price in thousands")
plt.ylabel("Sales in thousands")
plt.title("Price vs Sales")
plt.show()


#kurtosis
import numpy as np
from scipy.stats import kurtosis as k
profits=([100,120,150,200,4,1,2,5,3,2,6,5,4,3,3,1,2])
kurto=k(profits,fisher=True)
kurto1=k(profits,fisher=False)
mean_value=np.mean(profits)
max_value=max(profits)
min_value=min(profits)
if(kurto>0):
    print("heavy tail more distribution")
    if(max_value-mean_value)>(mean_value-min_value):
        print("big profits")
    else:
        print("big loss")
elif(kurto<0):
    print("low tail less distribution and low profit/loss")
else:
    print("normal distribution and normal profit/loss")


heavy tail more distribution
big profits

mean_val=np.mean(profits)
median_val=np.median(profits)
mean_val

np.float64(35.94117647058823)

plt.plot(profits, color="pink")
plt.title("Profit or Loss Distribution")
plt.xlabel("Profit Values")
plt.ylabel("Frequency")
plt.axhline(mean_val, linestyle="--", linewidth=3)
plt.axhline(median_val, linestyle="dotted", linewidth=2)
plt.show()

