# -*- coding: utf-8 -*-
"""Kurtosis.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1puOPVU9QtxOdnqtr4CaK8sEBTSqfJyRu#scrollTo=b3w9zCR6lFeF
"""


import pandas as pd
import numpy as np
