# -*- coding: utf-8 -*-
"""matplotib.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1szXlSf6oAohiSE-LK5Co78z389ytxoMW
"""

import pandas as pd
import numpy as np

data=pd.read_csv("Weather_Dataset.csv")
data.head(10)

import matplotlib.pyplot as plt
plt.plot(data["Temp_C"])
plt.title("Temperature",color="Red")
plt.xlabel("Hours")
plt.ylabel("Temperature (°C)")
plt.show()


plt.hist(data["Temp_C"])
plt.title("Temperature",color="Red")
plt.xlabel("Hours")
plt.ylabel("Temperature (°C)")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

chennai = [32, 45, 50, 60, 55, 70, 65, 80, 75, 68, 58, 50]
mumbai = [25, 40, 55, 90, 110, 120, 130, 125, 100, 70, 50, 35]
delhi = [10, 15, 25, 35, 50, 60, 65, 55, 40, 30, 20, 15]

plt.boxplot(
    [chennai, mumbai, delhi],
    labels=['Chennai', 'Mumbai', 'Delhi']
)
plt.title("Monthly Rainfall Comparison")
plt.xlabel("City")
plt.ylabel("Rainfall (cm)")
plt.show()

#RESULTS

Tamil = [32, 45, 50, 60, 55]
English = [ 55, 90,100, 70, 50]
SocialScience = [50, 60, 65, 55, 20, 15]

plt.boxplot([Tamil, English, SocialScience],
            labels=['Tamil', 'English', 'SocialScience'])
plt.title("MARKS")
plt.xlabel("Sub")
plt.ylabel("Scored Marks")
plt.show()


import matplotlib.pyplot as plt
Tamil = 85
English = 78
SocialScience = 90
subjects = ['Tamil', 'English', 'Social Science']
marks = [Tamil, English, SocialScience]
plt.pie(marks,labels=subjects,autopct='%1.1f%%',startangle=90)
plt.title("Subject Marks")
plt.show()


subjects = ['Tamil', 'English', 'Social Science']
marks = [Tamil, English, SocialScience]
plt.bar(subjects, marks)
plt.title("MARKS")
plt.xlabel("Subjects")
plt.ylabel("Scored Marks")
plt.show()

temps = np.array([
    [28, 36, 51],
    [27, 35, 30],
    [30, 37, 72],
    [40, 48, 33],
    [30, 39, 34],
    [50, 40, 55],
    [29, 57, 73]
])

plt.imshow(temps, cmap='OrRd', aspect='auto')
plt.colorbar(label="Temperature (°C)")
plt.title("Salem heat rate")
