# -*- coding: utf-8 -*-
"""matplotib1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1emndQXHGLVtwo2JYcqQM9lPcl-XHBnI3
"""

import pandas as pd
import numpy as np


df = pd.read_csv('/content/HR_Analytics.csv')
df
#Other one
data=pd.read_csv("HR_Analytics.csv")
data
x=data['Age']
y=data['DistanceFromHome']
import matplotlib.pyplot as plt
plt.scatter(x, y,color="skyblue")
plt.xlabel("Age")
plt.ylabel("Employee Satisfaction")
plt.title("Age vs Employee Satisfaction")
plt.show()

import matplotlib.pyplot as plt
plt.bar(x, y,color="Purple")
plt.xlabel("Age")
plt.ylabel("Employee Satisfaction")
plt.title("Age vs Employee Satisfaction")
plt.show()

x=data['Age']
y=data['EmployeeNumber']

import matplotlib.pyplot as plt
plt.hist(df["Age"],bins=10)
plt.xlabel("Age")
plt.ylabel("Number of Employees")
plt.title("Age vs EmployeeNumber")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("/content/HR_Analytics.csv")
x=df['Gender']
y=df['Age']
plt.bar(x,y,color="skyblue")
plt.xlabel("Gender")
plt.ylabel("Age")
plt.title("Gender By Age")
plt.show()
