# -*- coding: utf-8 -*-
"""regex.ipynb

Automatically generated by Colab.

Original file is located at
https://colab.research.google.com/drive/1eo6s1XaIvSm3QIMcFkejR3E2O4QDLIHX
"""

import re
text = "This is my Mail Bharathi123@gmail.com"
find = re.findall(r'\w+@\w+\.\w+', text)
print(find)

['Bharathi123@gmail.com']

import re
text = "This is my Mail Bharathi123@gmail.com"
find = re.findall(r'\w{2,}\d+@', text)
print(find)

['Bharathi123@']

import re
text="this is my email Bharathi@gmail.com and Brindha123@gmail.com and K123@gmail.com"
data=re.findall(r'\w{2,}+@\w{2,}\.\w{2,}',text)
data

['Bharathi@gmail.com', 'Brindha123@gmail.com', 'K123@gmail.com']

text = "This is my Mail Bharathi123@gmail.com"
answer = re.sub(r'Bharathi123@gmail.com',"$", text)
print(answer)

This is my Mail $

text = "This is my Mail Bharathi123@gmail.com"
answer = re.sub("$","mail", text)
print(answer)

This is my Mail Bharathi123@gmail.commail

text = "This is my Mail Bharathi123@gmail.com"
answer = re.search(r"mail", text)
print(answer)

<re.Match object; span=(29, 33), match='mail'>

text = "This is my Mail Bharathi123@gmail.com"
answer = re.search(r"Bharathi123@gmail.com", text)
print(answer)

<re.Match object; span=(16, 37), match='Bharathi123@gmail.com'>

name=input("Enter the Name")
data=re.findall(r'bharathi',name)
if data:
  print("data found")
else:
  print("data is not found")
data

Enter the Namebharathi
data found
['bharathi']

txt="I am working at sumatisons Private Limited and My position of Associate Software Developer....."
sse=re.search(r'Software',txt)
print(sse)

<re.Match object; span=(72, 80), match='Software'>

txt="my phone number is 044567890432"
se=re.search(r'\d{9,}',txt)
print(se)

<re.Match object; span=(19, 31), match='044567890432'>

txt="my phone number is 044567890432"
extract=re.search(r'\d{12,}',txt)
print(extract)

<re.Match object; span=(19, 31), match='044567890432'>

txt="my phone number is 044567890432"
se=re.search(r'\d{10,}',txt)
print(se.group())

044567890432

txt="My name is Bharathi.. I am studying at Jayalakshmi Institute of technology Under Periyar University"
replace=re.sub(r'Periyar',"Anna",txt)
print(replace)

My name is Bharathi.. I am studying at Jayalakshmi Institute of technology Under Anna University

