# -*- coding: utf-8 -*-
"""skew.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1zQ4QEYGqlPLKpQkyGUCgCH79HbmxmenK#scrollTo=KI5dVozU-L8l
"""

import numpy as np
import pandas as pd

data=pd.read_csv("employees.csv")
data

data=data["SALARY"]
data

from scipy.stats import skew
ans=skew(data)
if ans>0:
    print("positive skew")
elif ans<0:
    print("negative skew")
else:
    print("normal skew")

positive skew

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))
plt.hist(data, color='skyblue', bins=10)
plt.title("Salary Distribution")
plt.xlabel("Salary")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

import numpy as np
profits=[100,99,98,85,34,45,90,1,2,3]
data=np.array(profits)
data

array([100,  99,  98,  85,  34,  45,  90,   1,   2,   3])

from scipy.stats import skew
ans=skew(data)
if ans>0:
    print("positive skew")
elif ans<0:
    print("negative skew")
else:
    print("normal skew")

negative skew

import matplotlib.pyplot as plt
plt.hist(data,color="red",bins=16)
plt.title("negative skew")
plt.xlabel("Salary")
plt.grid()
plt.show()
